// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeakAppHandler.Notification.Api.Persistence;

#nullable disable

namespace WeakAppHandler.Notification.Api.Persistence.Migrations
{
    [DbContext(typeof(AlertingDbContext))]
    [Migration("20260902010433_InitialAlerting")]
    partial class InitialAlerting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeakAppHandler.Notification.Api.Domain.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meter_type");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_code");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<bool?>("ResolvedValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved_value_bool");

                    b.Property<decimal?>("ResolvedValueNumeric")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("resolved_value_numeric");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<bool?>("TriggeredValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("triggered_value_bool");

                    b.Property<decimal?>("TriggeredValueNumeric")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("triggered_value_numeric");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("TriggeredAt")
                        .IsDescending()
                        .HasDatabaseName("ix_alerts_triggered_at");

                    b.HasIndex("RuleId", "MeterId", "MetricCode")
                        .IsUnique()
                        .HasDatabaseName("ux_alerts_active_rule_meter_metric")
                        .HasFilter("status = 'active'");

                    b.ToTable("alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_alerts_resolution_complete", "(resolved_at IS NULL) = (status = 'active')");
                        });
                });

            modelBuilder.Entity("WeakAppHandler.Notification.Api.Domain.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CooldownSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300)
                        .HasColumnName("cooldown_seconds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("HysteresisPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(5.00m)
                        .HasColumnName("hysteresis_percent");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_triggered_at");

                    b.Property<string>("Location")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location");

                    b.Property<string>("MeterType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meter_type");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("operator");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<bool?>("ThresholdBool")
                        .HasColumnType("boolean")
                        .HasColumnName("threshold_bool");

                    b.Property<decimal?>("ThresholdNumeric")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("threshold_numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("MetricCode", "IsEnabled")
                        .HasDatabaseName("ix_alert_rules_metric_code_is_enabled");

                    b.ToTable("alert_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_alert_rules_cooldown_seconds", "cooldown_seconds >= 0");

                            t.HasCheckConstraint("ck_alert_rules_hysteresis_percent", "hysteresis_percent >= 0 AND hysteresis_percent <= 100");

                            t.HasCheckConstraint("ck_alert_rules_single_threshold", "(threshold_numeric IS NULL) <> (threshold_bool IS NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CooldownSeconds = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HysteresisPercent = 5.00m,
                            IsEnabled = true,
                            MetricCode = "co2",
                            Name = "CO2 above 1000 ppm",
                            Operator = "gt",
                            Severity = "warning",
                            ThresholdNumeric = 1000m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            CooldownSeconds = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HysteresisPercent = 5.00m,
                            IsEnabled = true,
                            MetricCode = "co2",
                            Name = "CO2 above 1400 ppm",
                            Operator = "gt",
                            Severity = "critical",
                            ThresholdNumeric = 1400m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            CooldownSeconds = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HysteresisPercent = 5.00m,
                            IsEnabled = true,
                            MetricCode = "pm25",
                            Name = "PM2.5 above 35 ug/m3",
                            Operator = "gt",
                            Severity = "warning",
                            ThresholdNumeric = 35m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            CooldownSeconds = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HysteresisPercent = 5.00m,
                            IsEnabled = true,
                            MetricCode = "humidity",
                            Name = "Humidity above 70%",
                            Operator = "gt",
                            Severity = "info",
                            ThresholdNumeric = 70m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            CooldownSeconds = 300,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            HysteresisPercent = 0m,
                            IsEnabled = true,
                            Location = "Garage",
                            MeterType = "motion",
                            MetricCode = "motion_detected",
                            Name = "Motion detected in Garage",
                            Operator = "eq",
                            Severity = "warning",
                            ThresholdBool = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("WeakAppHandler.Notification.Api.Domain.AlertRuleState", b =>
                {
                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("MetricCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_code");

                    b.Property<DateTimeOffset>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_triggered_at");

                    b.Property<bool>("WasBreaching")
                        .HasColumnType("boolean")
                        .HasColumnName("was_breaching");

                    b.HasKey("RuleId", "MeterId", "MetricCode")
                        .HasName("pk_alert_rule_state");

                    b.ToTable("alert_rule_state", (string)null);
                });

            modelBuilder.Entity("WeakAppHandler.Notification.Api.Domain.Alert", b =>
                {
                    b.HasOne("WeakAppHandler.Notification.Api.Domain.AlertRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_alert_rules_rule_id");
                });

            modelBuilder.Entity("WeakAppHandler.Notification.Api.Domain.AlertRuleState", b =>
                {
                    b.HasOne("WeakAppHandler.Notification.Api.Domain.AlertRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_rule_state_alert_rules_rule_id");
                });
#pragma warning restore 612, 618
        }
    }
}
