<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="HotChocolate.AspNetCore" Version="16.6.4" />
    <PackageVersion Include="HotChocolate.AspNetCore.CommandLine" Version="16.6.4" />
    <PackageVersion Include="HotChocolate.Data.EntityFramework" Version="16.6.4" />
    <PackageVersion Include="MassTransit.EntityFrameworkCore" Version="8.5.10" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.4" />
  </ItemGroup>
</Project>