// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeakAppHandler.Processor.Infrastructure.Persistence;

#nullable disable

namespace WeakAppHandler.Processor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeakAppHandler.Processor.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meter_type");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("Location", "MeterType")
                        .IsUnique()
                        .HasDatabaseName("ix_meters_location_meter_type");

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("WeakAppHandler.Processor.Domain.MeterCurrentState", b =>
                {
                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("MetricCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_code");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<bool?>("PreviousValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("previous_value_bool");

                    b.Property<decimal?>("PreviousValueNumeric")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("previous_value_numeric");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<decimal?>("ValueNumeric")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value_numeric");

                    b.HasKey("MeterId", "MetricCode")
                        .HasName("pk_meter_current_state");

                    b.HasIndex("MetricCode")
                        .HasDatabaseName("ix_meter_current_state_metric_code");

                    b.ToTable("meter_current_state", (string)null);
                });

            modelBuilder.Entity("WeakAppHandler.Processor.Domain.Metric", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("meter_type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("value_kind");

                    b.HasKey("Code")
                        .HasName("pk_metrics");

                    b.ToTable("metrics", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "energy",
                            DisplayName = "Energy",
                            MeterType = "energy",
                            Unit = "kWh",
                            ValueKind = "Numeric"
                        },
                        new
                        {
                            Code = "co2",
                            DisplayName = "CO2",
                            MeterType = "air_quality",
                            Unit = "ppm",
                            ValueKind = "Numeric"
                        },
                        new
                        {
                            Code = "pm25",
                            DisplayName = "PM2.5",
                            MeterType = "air_quality",
                            Unit = "µg/m³",
                            ValueKind = "Numeric"
                        },
                        new
                        {
                            Code = "humidity",
                            DisplayName = "Humidity",
                            MeterType = "air_quality",
                            Unit = "%",
                            ValueKind = "Numeric"
                        },
                        new
                        {
                            Code = "motion_detected",
                            DisplayName = "Motion Detected",
                            MeterType = "motion",
                            Unit = "—",
                            ValueKind = "Boolean"
                        });
                });

            modelBuilder.Entity("WeakAppHandler.Processor.Domain.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<bool>("IsChanged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_changed");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_id");

                    b.Property<string>("MetricCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric_code");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<decimal?>("ValueNumeric")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("value_numeric");

                    b.HasKey("Id")
                        .HasName("pk_readings");

                    b.HasIndex("MetricCode")
                        .HasDatabaseName("ix_readings_metric_code");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_readings_observed_at_brin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ObservedAt"), "brin");

                    b.HasIndex("MeterId", "MetricCode", "ObservedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_readings_meter_id_metric_code_observed_at");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("WeakAppHandler.Processor.Domain.MeterCurrentState", b =>
                {
                    b.HasOne("WeakAppHandler.Processor.Domain.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_current_state_meters_meter_id");

                    b.HasOne("WeakAppHandler.Processor.Domain.Metric", null)
                        .WithMany()
                        .HasForeignKey("MetricCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meter_current_state_metrics_metric_code");
                });

            modelBuilder.Entity("WeakAppHandler.Processor.Domain.Reading", b =>
                {
                    b.HasOne("WeakAppHandler.Processor.Domain.Meter", null)
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_meters_meter_id");

                    b.HasOne("WeakAppHandler.Processor.Domain.Metric", null)
                        .WithMany()
                        .HasForeignKey("MetricCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_metrics_metric_code");
                });
#pragma warning restore 612, 618
        }
    }
}
