// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeakAppHandler.Auth.Persistence;

#nullable disable

namespace WeakAppHandler.Auth.Persistence.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeakAppHandler.Auth.Domain.ServiceClient", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_secret_hash");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.HasKey("ClientId")
                        .HasName("pk_service_clients");

                    b.ToTable("service_clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = "gateway-ingestor",
                            ClientSecretHash = "100000.Gis8TV5vcIGSo7TF1uf4CQ==.OrPC+BZUxOWUbmqLAkWrWjWV2ywBF8W4wIUbz/zCkzQ=",
                            Scopes = new[] { "ingestion:admin" }
                        });
                });

            modelBuilder.Entity("WeakAppHandler.Auth.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Demo Viewer",
                            Email = "viewer@weakapphandler.local",
                            PasswordHash = "100000.TD8eepstTl9qe4ydDh8qOw==.Ms1151VCfO2qspjD7h8rp39VEvwnA1l7XGS8Qw4oNOM=",
                            Role = "viewer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Demo Admin",
                            Email = "admin@weakapphandler.local",
                            PasswordHash = "100000.n459bFtKOSgXBl9OPSwbCg==.B4IlZ6DiiU2KQhviWUUJeclTAHRtOcb+nO7IKu8KkOI=",
                            Role = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
