<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.RabbitMQ" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Shared/Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DataIngestorService.Tests" />
    </ItemGroup>

</Project>
